INSERT INTO T_FLO_ENDERECO(DS_LOGRADOURO,NR_ENDERECO,NM_COMPLEMENTO,NM_BAIRRO,NM_CIDADE,SG_ESTADO,NR_CEP) 
VALUES ('Av. Lins de Vasconcelos','1222 e 1264','','Aclimação','São Paulo', 'SP', '01538-001');

INSERT INTO T_FLO_ENDERECO(DS_LOGRADOURO,NR_ENDERECO,NM_COMPLEMENTO,NM_BAIRRO,NM_CIDADE,SG_ESTADO,NR_CEP) 
VALUES ('Av. Paulista','1106','6º e 7º andar','Cerqueira César','São Paulo', 'SP', '01311-000');

INSERT INTO T_FLO_ENDERECO(DS_LOGRADOURO,NR_ENDERECO,NM_COMPLEMENTO,NM_BAIRRO,NM_CIDADE,SG_ESTADO,NR_CEP) 
VALUES ('Rua Olimpíadas','186','','Vila Olímpia','São Paulo', 'SP', '04551-000');

INSERT INTO T_FLO_ENDERECO(DS_LOGRADOURO,NR_ENDERECO,NM_COMPLEMENTO,NM_BAIRRO,NM_CIDADE,SG_ESTADO,NR_CEP) 
VALUES ('Alameda Araguaia','1142','Bloco 4','Alphaville','Barueri', 'SP', '06453-001');

INSERT INTO T_FLO_ENDERECO(DS_LOGRADOURO,NR_ENDERECO,NM_COMPLEMENTO,NM_BAIRRO,NM_CIDADE,SG_ESTADO,NR_CEP) 
VALUES ('Avenida Prof. Almeida Prado','1280','','Butantã','São Paulo', 'SP', '05508-900');

INSERT INTO T_FLO_ENDERECO(DS_LOGRADOURO,NR_ENDERECO,NM_COMPLEMENTO,NM_BAIRRO,NM_CIDADE,SG_ESTADO,NR_CEP) 
VALUES ('Av. Líder','1495','','Cidade Líder','São Paulo', 'SP', '08280-000');


INSERT INTO T_FLO_INSTITUICAO(NM_INSTITUICAO,DS_TIPO_INSTITUICAO,DS_INSTITUICAO,IMG_INSTITUICAO)
VALUES('FIAP','PRIVADO','A FIAP é o centro de excelência em tecnologia mais respeitado do país. Uma história que vem sendo construída dia após dia, estimulando mentes a vivenciarem a inovação e o empreendedorismo.','/Faculdade/logo-fiap.jpg');

INSERT INTO T_FLO_INSTITUICAO(NM_INSTITUICAO,DS_TIPO_INSTITUICAO,DS_INSTITUICAO,IMG_INSTITUICAO)
VALUES('USP','PUBLICO','A Universidade de São Paulo (USP) é uma universidade pública, mantida pelo Estado de São Paulo e ligada à Secretaria de Desenvolvimento Econômico, Ciência, Tecnologia e Inovação (SDECTI)','/Faculdade/logo-usp.png');

INSERT INTO T_FLO_INSTITUICAO(NM_INSTITUICAO,DS_TIPO_INSTITUICAO,DS_INSTITUICAO,IMG_INSTITUICAO)
VALUES('UNIP','PRIVADO','A UNIP promove a formação atualizada dos alunos e sua capacitação para uma sociedade em mudança, por meio de um ensino de qualidade.','/Faculdade/logo-unip.jpg');

INSERT INTO T_FLO_INSTITUICAO_UNIDADE(cd_instituicao,cd_endereco) VALUES (1,1);
INSERT INTO T_FLO_INSTITUICAO_UNIDADE(cd_instituicao,cd_endereco) VALUES (1,2);
INSERT INTO T_FLO_INSTITUICAO_UNIDADE(cd_instituicao,cd_endereco) VALUES (1,3);
INSERT INTO T_FLO_INSTITUICAO_UNIDADE(cd_instituicao,cd_endereco) VALUES (1,4);
INSERT INTO T_FLO_INSTITUICAO_UNIDADE(cd_instituicao,cd_endereco) VALUES (2,5);
INSERT INTO T_FLO_INSTITUICAO_UNIDADE(cd_instituicao,cd_endereco) VALUES (3,6);

INSERT INTO T_FLO_CATALOGO (DS_CATALOGO) VALUES ('TI');
INSERT INTO T_FLO_CATALOGO (DS_CATALOGO) VALUES ('HUMANAS');
INSERT INTO T_FLO_CATALOGO (DS_CATALOGO) VALUES ('EXATAS');

INSERT INTO T_FLO_CURSO (CD_CATALOGO,NM_CURSO) VALUES (1,'ANALISE E DESENVOLVIMENTO DE SISTEMAS');
INSERT INTO T_FLO_CURSO (CD_CATALOGO,NM_CURSO) VALUES (1,'BANCO DE DADOS');
INSERT INTO T_FLO_CURSO (CD_CATALOGO,NM_CURSO) VALUES (1,'JOGOS DIGITAIS');
INSERT INTO T_FLO_CURSO (CD_CATALOGO,NM_CURSO) VALUES (2,'ADMINISTRACAO');
INSERT INTO T_FLO_CURSO (CD_CATALOGO,NM_CURSO) VALUES (2,'DIREITO');
INSERT INTO T_FLO_CURSO (CD_CATALOGO,NM_CURSO) VALUES (2,'JORNALISMO');
INSERT INTO T_FLO_CURSO (CD_CATALOGO,NM_CURSO) VALUES (3,'MATEMATICA');
INSERT INTO T_FLO_CURSO (CD_CATALOGO,NM_CURSO) VALUES (3,'ENGENHARIA CIVIL');
INSERT INTO T_FLO_CURSO (CD_CATALOGO,NM_CURSO) VALUES (3,'QUIMICA');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(1,1,5,0,0,2,'TECNOLOGO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(2,1,5,0,0,2,'GRADUACAO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(3,1,5,0,0,2.5,'MBA');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(1,2,5,0,0,3,'GRADUACAO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(2,2,5,0,0,4,'TECNOLOGO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(5,2,5,0,0,4,'GRADUACAO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(6,2,5,0,0,5,'GRADUACAO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(1,3,5,0,0,5,'TECNOLOGO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(2,3,5,0,0,4,'GRADUACAO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(3,3,5,0,0,4,'TECNOLOGO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(4,3,5,0,0,4,'GRADUACAO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(5,3,5,0,0,5,'GRADUACAO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(6,3,5,0,0,5,'GRADUACAO');

INSERT INTO T_FLO_INSTITUICAO_CURSO (CD_CURSO,CD_INSTITUICAO,NR_NOTA_MEC,ST_BOLSA,VL_BOLSA,TP_CURSO,DS_TIPO_CURSO)
VALUES(7,3,5,0,0,3,'GRADUACAO');

INSERT INTO T_FLO_TIPO_USUARIO (DS_TIPO_USUARIO) VALUES ('ADM');



















