SELECT t1.cd_instituicao,
       t3.ds_logradouro,
       t3.nr_endereco 
FROM T_FLO_INSTITUICAO T1 
LEFT JOIN T_FLO_INSTITUICAO_UNIDADE T2 ON T1.CD_INSTITUICAO = T2.CD_INSTITUICAO
LEFT JOIN T_FLO_ENDERECO T3 ON T2.CD_ENDERECO = T3.CD_ENDERECO;

SELECT T1.* FROM T_FLO_CURSO;
SELECT * FROM T_FLO_INSTITUICAO;

SELECT 
    t2.cd_curso,
    t2.nm_curso,
    t1.nr_nota_mec,
    t1.nr_nota_mec,
    t3.ds_instituicao,
    t3.img_instituicao
FROM T_FLO_INSTITUICAO_CURSO T1
INNER JOIN T_FLO_CURSO T2 ON T1.CD_CURSO = T2.CD_CURSO
INNER JOIN T_FLO_INSTITUICAO T3 ON T1.CD_INSTITUICAO = T3.CD_INSTITUICAO;
